### ISSUE TITLE
Improve styling of the form and the footer.

### ISSUE THREAD

**Issue by garimasingh128** [Catalyst-SMVD/OpenSourceEvents-Frontend#17]

**Comment by aryamanpuri** [comment]
Hi @garimasingh128 . Thanks for opening issue. What kind of styling issue are you facing in the form and Footer?

**Comment by garimasingh128** [comment]
I was just thinking if we could add a colour scheme to whole website as now it looks quite random. We could also add a detailed footer and a form that follows the design.

**Comment by aryamanpuri** [comment]
Yes, ur right. 
There is no color scheme decided yet and the footer just consists of icons. 
I am assigning this issue to you and would like to see your creativity.
And join the [discord server]( https://discord.gg/dHtDhHa).
