### ISSUE TITLE
create a new page for contact and removing it from main frontend page.

### ISSUE THREAD

**Issue by Amankumar29** [Catalyst-SMVD/OpenSourceEvents-Frontend#26]
**create a new page for contact and remove it from main front-end page.**

1. for the new page make the background more attractive.
2. place the part in the middle of the page.
3. let the navbar be present as same as in the main page.
4. same with the footer.

**Comment by Amankumar29** [comment]
@codetheorem @vinayaksh42 both of you can do this work.  :)

**Comment by vinayaksh42** [comment]
Sure sir @Amankumar29
