### ISSUE TITLE
Techstack

### ISSUE THREAD

**Issue by aryamanpuri** [Catalyst-SMVD/OpenSourceEvents-Frontend#3]
Techstack of the website is upon discussion.
@aashimgarg @anubhavsingh16

**Comment by aashimgarg** [comment]
I think logo is yet to be decided first.

**Comment by aryamanpuri** [comment]
Ur views regarding tech stack

**Comment by aashimgarg** [comment]
[image: orgLogo.png]

**Comment by aashimgarg** [comment]
HTML , CSS , VanillaJS finalised.
