### ISSUE TITLE
About Us page

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-SMVD/OpenSourceEvents-Frontend#41]
## Description
Add About us page and write all the necessary things about  Catalyst organization. Keep it simple like in `Mock`.

## Mocks
![about us](https://user-images.githubusercontent.com/47811606/82155133-43e4c480-9890-11ea-9d64-baca093676ec.png)
## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by Bindusar1212** [comment]
Can i do this one?

**Comment by anubhavsingh16** [comment]
okk

**Comment by deepdarshan21** [comment]
can I work on it

**Comment by Bindusar1212** [comment]
@anubhavsingh16  @aashimgarg 
![Screenshot 2020-05-20 at 4 12 50 PM](https://user-images.githubusercontent.com/59837391/82437471-12990e00-9ab5-11ea-8e15-69537781d051.png)
![Screenshot 2020-05-20 at 3 43 22 PM](https://user-images.githubusercontent.com/59837391/82437478-14fb6800-9ab5-11ea-9112-0e6369925f7e.png)

**Comment by anubhavsingh16** [comment]
> can I work on it

sorry @deepdarshan21 this issue just solved you can pick any other issue for issue list.
Thank You.
