### ISSUE TITLE
Rename Document

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-SMVD/OpenSourceEvents-Frontend#43]
## Description
Rename Document to `Our Team` and add members of Catalyst.
take style reference from https://smvduclub.github.io/main_page/
## Mocks
![team](https://user-images.githubusercontent.com/47811606/82155670-3e897900-9894-11ea-8c63-1225bd056dfb.png)

### Update [Required]
- [x] [add members of Catalyst]
- [x] [connect with Our team button]

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by Amankumar29** [comment]
i will take this up

**Comment by Amankumar29** [comment]
do we have to make different page or include it in the same?

**Comment by anubhavsingh16** [comment]
Read issue description carefully 😉
